# Generated by Django 4.1.3 on 2022-11-24 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_post_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("text", models.TextField(verbose_name="Комментарий")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            11,
                            24,
                            15,
                            14,
                            3,
                            841692,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Одобрен?",
                    ),
                ),
                (
                    "approved_comments",
                    models.BooleanField(default=False, verbose_name="Одобрен?"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарий",
            },
        ),
    ]
