# Generated by Django 4.1.3 on 2022-11-28 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 28, 20, 45, 24, 960186, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Одобрен?",
            ),
        ),
    ]
