# Generated by Django 4.1.3 on 2022-11-30 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_comment_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 30, 13, 33, 9, 667556, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Одобрен?",
            ),
        ),
    ]
